# config.toml

[database]
host = "localhost"
port = 3306
user = "yourusername"
password = "yourpassword"
database = "yourdatabase"

[plugin]
name = "PvP-Stats"  # Default plugin name, can be customized